
#Q2

SELECT PRODUCTS.ProductID, ProductS.Name,ProductS.Cost AS price, CATEGORIES.Type AS category_title FROM PRODUCTS 
LEFT JOIN PRODUCTS_CATEGORIES ON PRODUCTS.ProductID = PRODUCTS_CATEGORIES.ProductID
LEFT JOIN CATEGORIES ON CATEGORIES.CategoryID = PRODUCTS_CATEGORIES.CategoryID ORDER BY Timestamp;


#Q3

SELECT PRODUCTS.ProductID, PRODUCTS.Name FROM PRODUCTS
WHERE PRODUCTS.ProductID NOT IN (
SELECT PRODUCTS.ProductID FROM PRODUCTS 
INNER JOIN IMAGES ON PRODUCTS.ProductID = IMAGES.ProductID);

#Q4

SELECT c.Type,
IF (c.ParentCategory = 0, 'Top Category',c1.Type) AS ParentCategory
FROM CATEGORIES c
LEFT JOIN CATEGORIES c1
ON c.ParentCategory = c1.CategoryID ORDER BY ParentCategory;


#q5
SELECT CATEGORIES.CategoryID,CATEGORIES.Type, CATEGORIES.ParentCategory FROM CATEGORIES WHERE CATEGORIES.CategoryID NOT IN 
(SELECT CATEGORIES.ParentCategory FROM CATEGORIES);

#Q6
SELECT PRODUCTS.Name,PRODUCTS.Cost AS price, PRODUCTS.Description, CATEGORIES.Type AS category_title FROM PRODUCTS  
LEFT JOIN PRODUCTS_CATEGORIES ON PRODUCTS.ProductID = PRODUCTS_CATEGORIES.ProductID
LEFT JOIN CATEGORIES ON CATEGORIES.CategoryID = PRODUCTS_CATEGORIES.CategoryID WHERE CATEGORIES.Type = 'Mobiles';

#Q7
SELECT * FROM PRODUCTS WHERE Quantity < 30 ;

#Q8
UPDATE PRODUCTS SET QUANTITY = QUANTITY + 10 
WHERE 1;
