
#Q2
SELECT PRODUCTS_ORDERS.OrderID, COUNT(PRODUCTS_ORDERS.OrderID) AS Total_Product, SUM(PRODUCTS.Cost) AS Total_cost 
FROM PRODUCTS_ORDERS
LEFT JOIN PRODUCTS
ON PRODUCTS_ORDERS.ProductID=PRODUCTS.ProductID 
GROUP BY PRODUCTS_ORDERS.OrderID 
ORDER BY Total_cost 
DESC LIMIT 10;

#Q1
SELECT t.OrderID, ORDERS.PlacedDate, t.Total_cost FROM 
(SELECT PRODUCTS_ORDERS.OrderID, COUNT(PRODUCTS_ORDERS.OrderID) AS Total_Product, SUM(PRODUCTS.Cost) AS Total_cost
FROM PRODUCTS_ORDERS
LEFT JOIN PRODUCTS
ON PRODUCTS_ORDERS.ProductID=PRODUCTS.ProductID 
GROUP BY PRODUCTS_ORDERS.OrderID) AS t
LEFT JOIN ORDERS
ON
t.OrderID=ORDERS.OrderID ORDER BY ORDERS.PlacedDate DESC LIMIT 50;

#Q3
SELECT t.OrderID, t.PlacedDate, t.State FROM
(SELECT ORDERS.OrderID,ORDERS.PlacedDate,PRODUCTS_ORDERS.State FROM ORDERS
LEFT JOIN PRODUCTS_ORDERS
ON ORDERS.OrderID = PRODUCTS_ORDERS.OrderID) AS t
WHERE t.PlacedDate < CURRENT_DATE - INTERVAL '10' DAY AND CURRENT_DATE;


#Q4
SELECT ORDERS.OrderID, ORDERS.PlacedDate FROM ORDERS
WHERE  ORDERS.PlacedDate NOT IN(
SELECT ORDERS.PlacedDate FROM ORDERS
RIGHT JOIN USERS
ON ORDERS.UserID = USERS.UserID
WHERE ORDERS.PlacedDate > CURRENT_DATE - INTERVAL + '2' MONTH AND CURRENT_DATE);

#Q5
SELECT USERS.UserID, ORDERS.OrderID, ORDERS.PlacedDate FROM ORDERS
RIGHT JOIN USERS
ON ORDERS.UserID = USERS.UserID
WHERE ORDERS.PlacedDate between CURRENT_DATE - INTERVAL+ '15' DAY AND CURRENT_DATE;

#Q6
SELECT u.OrderID, u.state, PRODUCTS.ProductID, PRODUCTS.Name
FROM(
SELECT t.OrderID, t.PlacedDate, t.State, t.ProductID FROM
(SELECT ORDERS.OrderID,ORDERS.PlacedDate,PRODUCTS_ORDERS.State, PRODUCTS_ORDERS.ProductID  FROM ORDERS
LEFT JOIN PRODUCTS_ORDERS
ON ORDERS.OrderID = PRODUCTS_ORDERS.OrderID) AS t
WHERE t.State LIKE '%Shipped%')as u
LEFT JOIN PRODUCTS
ON
u.ProductID = PRODUCTS.ProductID
WHERE u.OrderID = 2;


#Q7
SELECT u.OrderID, u.state, PRODUCTS.ProductID, PRODUCTS.Name, PRODUCTS.Cost
FROM(
SELECT t.OrderID, t.PlacedDate, t.State, t.ProductID FROM
(SELECT ORDERS.OrderID,ORDERS.PlacedDate,PRODUCTS_ORDERS.State, PRODUCTS_ORDERS.ProductID  FROM ORDERS
LEFT JOIN PRODUCTS_ORDERS
ON ORDERS.OrderID = PRODUCTS_ORDERS.OrderID) AS t
)as u
LEFT JOIN PRODUCTS
ON
u.ProductID = PRODUCTS.ProductID
WHERE PRODUCTS.Cost > 30 AND PRODUCTS.Cost < 250;

#Q8
UPDATE PRODUCTS_ORDERS 
INNER JOIN ORDERS ON PRODUCTS_ORDERS.OrderID=ORDERS.OrderID
SET PRODUCTS_ORDERS.State = 'Shipped'
WHERE ORDERS.PlacedDate = '2018-12-03';

SELECT PRODUCTS_ORDERS.OrderID, PRODUCTS_ORDERS.State FROM PRODUCTS_ORDERS 
INNER JOIN ORDERS 
ON PRODUCTS_ORDERS.OrderID=ORDERS.OrderID
WHERE ORDERS.PlacedDate = '2018-12-03';
