
USE storefront;

#Q1
DELIMITER $$
CREATE PROCEDURE RETRIVE_AVERAGE_SALES (Month INT , Year INT)
BEGIN
SELECT  PRODUCTS.ProductID,PRODUCTS.Name, PRODUCTS.Brand, PRODUCTS.Cost, SUM(PRODUCTS.Cost) AS TotalSaleInMonth FROM
(SELECT T.OrderID , ProductID FROM
(SELECT OrderID FROM ORDERS
WHERE MONTH(PlacedDate) = Month AND YEAR(PlacedDate) = Year) AS T
INNER JOIN PRODUCTS_ORDERS
WHERE PRODUCTS_ORDERS.OrderID = T.OrderID) AS L
JOIN PRODUCTS
WHERE PRODUCTS.ProductID = L.ProductID
GROUP BY ProductID;
END
$$

CALL RETRIVE_AVERAGE_SALES(12,2018);

#Q2
DELIMITER $$
CREATE PROCEDURE ORDERS_STATUS_BETWEEN (StartDate DATE , EndDate DATE)
BEGIN
DECLARE Days INT;
SET DAYS = EXTRACT(MONTH FROM EndDate);
SET StartDate = IF(StartDate > EndDate, CONCAT(DATE_FORMAT(EndDate, '%Y-%m-'), '01'), StartDate);
SELECT T.OrderID, ProductID , State FROM 
(SELECT OrderID FROM ORDERS
WHERE PlacedDate BETWEEN StartDate AND EndDate) AS T
LEFT JOIN PRODUCTS_ORDERS
ON T.OrderID = PRODUCTS_ORDERS.OrderID;
END
$$

CALL ORDERS_STATUS_BETWEEN('2018-12-1', '2018-12-28');
CALL ORDERS_STATUS_BETWEEN('2019-12-1', '2018-12-28');
